### ISSUE TITLE
Additional steps to get docker-compose working

### ISSUE THREAD

**Issue by jaden** [andreimarcu/linx-server#218]
When I followed the instructions in the README I ran into a few issues. I thought these tips might be added to the README to help others avoid them.

First, I set permissions on the local files and meta folders to nobody:nogroup to stop the permission denied errors when uploading a file. 

`chown 65534:65534 files/ meta/`

Second, I enabled docker with systemctl to restart the app after a server reboot.

`systemctl enable docker`

Also, it would have been helpful to have the command to start the app and run it in the background, i.e. `docker-compose up -d`

I'd be happy to submit a PR if these steps are useful.

**Comment by andreimarcu** [comment]
Thanks, however given how different environments can be, this is out of scope for the time being

**Comment by kevingimbel** [comment]
I just had the exact same issue.

Running linx with docker-compose I had to either set the folder permissions to 777 (bad) or use do the following

```
chown nobody:nogroup files/ 
chown nobody:nogroup meta/
```

Even then I still needed 775 permissions for uploading to work. Is there any general recommendation for permission setup? My gut feeling tells me 664 should be enough.

**Comment by andreimarcu** [comment]
I'll actually update the image and docs with more info to make it more accessible

**Comment by kevingimbel** [comment]
@andreimarcu Thanks!

**Comment by orangethakkali** [comment]
I have this on my docker-compose
```
version: '2.2'
services:
  linx-server:
    container_name: linx-server
    image: andreimarcu/linx-server
    entrypoint: /usr/local/bin/linx-server
    command: -config /data/linx-server.conf
    volumes:
      - ./files:/data/files
      - ./meta:/data/meta
      - /opt/linx/linx-server.conf:/data/linx-server.conf
    network_mode: bridge
    ports:
      - "8580:8080"
    restart: unless-stopped
```
![image](https://user-images.githubusercontent.com/7847452/91642170-c57aef80-ea46-11ea-8225-4094f884065a.png)

Still getting permission denied error, what am I doing wrong.
