### ISSUE TITLE
Docker container config path not exposed

### ISSUE THREAD

**Issue by BoKKeR** [andreimarcu/linx-server#220]
There is no way to set a config when using the docker container as there is no default path the linx-server would be looking for. Only way to set it is if I edit the dockerfile.

**Comment by andreimarcu** [comment]
You can pick any place to mount your config file.

Here's an example docker-compose for how you would do it:

```yml
version: '2.2'
services:
  linx-server:
    container_name: linx-server
    image: andreimarcu/linx-server
    entrypoint: /usr/local/bin/linx-server
    command: -config /config/linx-server.ini
    volumes:
      - /path/to/my/linx-server.ini:/config/linx-server.ini
      - /path/to/files:/data/files
      - /path/to/meta:/data/meta
    network_mode: bridge
    ports:
      - "8080:8080"
    restart: unless-stopped
```
