### ISSUE TITLE
Mistaking conf for directory?

### ISSUE THREAD

**Issue by ssh-rsa** [andreimarcu/linx-server#232]
I have tried spinning up a container using Docker compose but for some reason it is mistaking the .conf file as a directory?  I'm unsure if I misconfigured something.  
![image](https://user-images.githubusercontent.com/56268450/87830716-aa19a380-c84f-11ea-8763-7fa58dbc1825.png)

Here's my linx-server.conf

```
kylia@obelisk:~$ cat /mnt/oink/LNX/LNX.conf
bind = 127.0.0.1:8080
sitename = test
siteurl = http://$domain/
selifpath = selif
maxsize = 4294967296
maxexpiry = 86400
allowhotlink = true
remoteuploads = true
nologs = true
force-random-filename = false
cleanup-every-minutes = 5
filespath = files/
metapath = meta/
fastcgi = true
```

and my docker-compose.YAML 

```
kylia@obelisk:~$ cat docker-compose.yml
version: '2.2'
services:
 linx-server:
  container_name: LNX_SVR
  image: andreimarcu/linx-server
  entrypoint: /usr/local/bin/linx-server
  command: -config /mnt/oink/LNX/LNX.conf
  volumes:
  - /path/to/files:/mnt/oink/LNX/files
  - /path/to/meta:/mnt/oink/LNX/meta
  - /path/to/linx-server.conf:/mnt/oink/LNX/LNX.conf
  network_mode: bridge
  ports:
  - "8080:8080"
  restart: unless-stopped
```
