### ISSUE TITLE
Nginx Reverse Proxy Timeout.

### ISSUE THREAD

**Issue by TheGreatestJannet** [andreimarcu/linx-server#233]
Hello when running though a nginx reverse proxy the connection just times out (504 Gateway Time-out) this doesn't happen when connecting directly to it. My Nginx config is:
```
server{
        listen 80;
        server_name ;

        # Uncomment to redirect HTTP to HTTPS
        return 301 https://$host$request_uri;
}

server {
        listen *:443 ssl;
        server_name ;

        real_ip_header X-Real-IP;
        real_ip_recursive on;

        client_max_body_size 10240M;
        location / {
                fastcgi_pass 127.0.0.1:8085;
                include /etc/nginx/fastcgi_params;
        }

    ssl_certificate /etc/nginx/certs/wildcard.servername/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/wildcard.servername/key.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```
I'm using docker and my configs are: 
```
version: '2.2'
services:
  linx-server:
    container_name: linx-server
    image: ruimartinsptl/linx-server
    #entrypoint: /usr/local/bin/linx-server 
    command: /usr/local/bin/linx-server -config /data/linx-server.conf
    volumes:
      - /mnt/sda1/linx-server/files:/data/files
      - /mnt/sda1/linx-server/meta:/data/meta
      - /home/user/linx-server/linx-server.conf:/data/linx-server.conf
    network_mode: bridge
    ports:
      - "8085:8080"
    restart: unless-stopped
```
and
```
bind = 0.0.0.0:8080
sitename = Linx_Server
siteurl = https://servername
selifpath = selif
maxsize = 10737418240
maxexpiry = 172800
allowhotlink = true
remoteuploads = true
nologs = true
force-random-filename = false
#cleanup-every-minutes = 5
fastcgi = true
realip = true
```
Anyone know why it is timing out? If I use proxy_pass instead I get 400 errors and it doesn't upload files or pastebins.
